spring:
  datasource:
    url: jdbc:h2:file:./db
    username: user
    password: p
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2

springdoc:
  swagger-ui:
    path: /ui
  api-docs:
    path: /api